(() => {
  'use strict';
  const $=id=>document.getElementById(id), catalog=window.MONSTERS;
  // Collection order is independent of the user-defined order inside tiers.
  const sugared = new Set('assault bad-apple electric-blue extra-strength-black-ice extra-strength-super-dry gronk juice-aussie-lemonade juice-khaos juice-ripper juice-strawberry-lemonade khaotic lh44 mango-loco mixxd-core mixxd-punch monarch mule nitro-cosmic-peach nitro-super-dry nitrous-anti-gravity nitrous-killer-b orange-dreamsicle pacific-punch papillon-punch pipeline-punch punch-ballers-blend punch-mad-dog reserve-kiwi-strawberry reserve-orange-dreamsicle reserve-peaches-creme reserve-watermelon reserve-white-pineapple rio-punch strawberry-shot viking-berry voodoo-grape vr46-doctor'.split(' '));
  const coffee = new Set('farmers-oats irish-blend loca-moca mean-bean salted-caramel'.split(' '));
  const group=id=>id==='original'?0:id==='zero-sugar'?1:sugared.has(id)?2:id.startsWith('ultra-')||id==='zero-ultra'?3:id.startsWith('java-')||id.startsWith('killer-brew-')||coffee.has(id)?4:id.startsWith('rehab-')?5:6;
  catalog.sort((a,b)=>group(a.id)-group(b.id)||a.name.localeCompare(b.name,'en'));
  const collectionOrder=new Map(catalog.map((item,index)=>[item.id,index]));
  const sortPool=items=>items.sort((a,b)=>collectionOrder.get(a)-collectionOrder.get(b));
  const byId=new Map(catalog.map(item=>[item.id,item]));
  const key='monster-tier.v1'; let dragged=null, toastTimer, pending=null;
  const fresh=()=>({format:'monster-tier',version:1,title:'My Monster tier list',tiers:[['S','#f59895'],['A','#f4bc7a'],['B','#ebd779'],['C','#aed284'],['D','#86bcb6'],['F','#aaa0cf']].map(([name,color],i)=>({id:'tier-'+i,name,color,items:[]})),pool:catalog.map(i=>i.id)});
  function validate(raw) {
    if(!raw||raw.format!=='monster-tier'||raw.version!==1||typeof raw.title!=='string'||raw.title.length>70||!Array.isArray(raw.tiers)||raw.tiers.length<1||raw.tiers.length>15||!Array.isArray(raw.pool)) throw Error('This tier list format is not supported.');
    const seen=new Set(), tierIds=new Set();
    const list=items=>{if(!Array.isArray(items)) throw Error('Invalid tier data.'); return items.map(id=>{if(typeof id!=='string'||!byId.has(id)) throw Error('This file contains flavors that are not in this collection.');if(seen.has(id)) throw Error('The tier list contains duplicate cans.');seen.add(id);return id;});};
    const tiers=raw.tiers.map(t=>{if(!t||typeof t.id!=='string'||!/^tier-[a-z0-9-]{1,60}$/.test(t.id)||tierIds.has(t.id)||typeof t.name!=='string'||t.name.length<1||t.name.length>18||!/^#[0-9a-f]{6}$/i.test(t.color)) throw Error('Invalid tier data.');tierIds.add(t.id);return {id:t.id,name:t.name,color:t.color,items:list(t.items)};});
    const pool=list(raw.pool);for(const item of catalog)if(!seen.has(item.id))pool.push(item.id);
    return {format:'monster-tier',version:1,title:raw.title==='Mijn Monster tierlijst'?'My Monster tier list':raw.title,tiers,pool:sortPool(pool)};
  }
  let state=fresh(),loadError='';
  try{const saved=localStorage.getItem(key);if(saved) state=validate(JSON.parse(saved));}catch{loadError='Your saved list could not be loaded. Import a previous PNG backup to restore it.';}
  function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6500);}
  function save(){sortPool(state.pool);try{localStorage.setItem(key,JSON.stringify(state));$('saved').textContent='Saved locally';}catch{$('saved').textContent='Local saving unavailable';toast('Your browser is blocking local storage. Export a PNG to save your list.');}}
  function card(id){const item=byId.get(id),button=document.createElement('button');button.type='button';button.className='card';button.draggable=true;button.dataset.id=id;button.title=item.name;button.setAttribute('aria-label',item.name+' — move');const img=new Image();img.src=item.data;img.alt=item.name;img.draggable=false;button.append(img);button.addEventListener('click',()=>choose(id));button.addEventListener('dragstart',event=>{dragged=id;button.classList.add('dragging');event.dataTransfer.setData('text/plain',id);event.dataTransfer.effectAllowed='move';});button.addEventListener('dragend',()=>{dragged=null;button.classList.remove('dragging');document.querySelectorAll('.over').forEach(el=>el.classList.remove('over'));});return button;}
  function dropzone(el,target){el.addEventListener('dragover',e=>{if(!dragged)return;e.preventDefault();e.dataTransfer.dropEffect='move';el.classList.add('over');});el.addEventListener('dragleave',e=>{if(!el.contains(e.relatedTarget))el.classList.remove('over');});el.addEventListener('drop',e=>{e.preventDefault();el.classList.remove('over');const id=dragged;if(!id||!byId.has(id))return;const before=e.target.closest('.card')?.dataset.id;move(id,target,before);dragged=null;});}
  function move(id,target,before){if(id===before)return;const list=target==='pool'?state.pool:state.tiers.find(t=>t.id===target)?.items;if(!list)return;for(const items of [state.pool,...state.tiers.map(t=>t.items)]){const i=items.indexOf(id);if(i!==-1)items.splice(i,1);}const at=before?list.indexOf(before):-1;if(at<0)list.push(id);else list.splice(at,0,id);save();render();toast(byId.get(id).name+' moved.');}
  function ask(title,text,action){pending=action;$('confirm-title').textContent=title;$('confirm-text').textContent=text;$('confirm').showModal();}
  $('cancel').onclick=()=>{$('confirm').close();pending=null;};$('accept').onclick=()=>{const action=pending;pending=null;$('confirm').close();action?.();};$('confirm').addEventListener('cancel',()=>pending=null);
  function render(){
    $('title').value=state.title;$('board').replaceChildren();
    for(const tier of state.tiers){const row=document.createElement('div');row.className='tier';row.style.setProperty('--tier-color',tier.color);const label=document.createElement('div');label.className='tier-label';const name=document.createElement('input');name.className='tier-name';name.value=tier.name;name.maxLength=18;name.setAttribute('aria-label','Name of tier '+tier.name);name.addEventListener('change',()=>{tier.name=name.value.trim()||tier.name;name.value=tier.name;save();});const tools=document.createElement('div');tools.className='tier-tools';const color=document.createElement('input');color.type='color';color.value=tier.color;color.setAttribute('aria-label','Color of tier '+tier.name);color.addEventListener('input',()=>{tier.color=color.value;row.style.setProperty('--tier-color',tier.color);save();});const remove=document.createElement('button');remove.textContent='×';remove.title='Remove tier';remove.setAttribute('aria-label','Tier '+tier.name+' — remove');remove.onclick=()=>{if(state.tiers.length===1){toast('Keep at least one tier.');return;}ask('Tier '+tier.name+' — remove this tier?','The cans will return to the collection.',()=>{state.pool.push(...tier.items);state.tiers=state.tiers.filter(t=>t!==tier);save();render();});};tools.append(color,remove);label.append(name,tools);const zone=document.createElement('div');zone.className='tier-zone';zone.setAttribute('aria-label','Tier '+tier.name);dropzone(zone,tier.id);tier.items.forEach(id=>zone.append(card(id)));if(!tier.items.length){const hint=document.createElement('span');hint.className='hint';hint.textContent='Drop your cans here';zone.append(hint);}row.append(label,zone);$('board').append(row);}
    renderPool();$('ranked').textContent=(catalog.length-state.pool.length)+' / '+catalog.length+' ranked';$('add').disabled=state.tiers.length>=15;
  }
  function renderPool(){const query=$('search').value.trim().toLowerCase();const items=state.pool.filter(id=>byId.get(id).name.toLowerCase().includes(query));$('pool').replaceChildren(...items.map(card));$('count').textContent=state.pool.length;$('empty').hidden=items.length>0;$('empty').textContent=state.pool.length===0?'Everything has a place. Time to export your list!':'No flavors found.';}
  function choose(id){$('picker-title').textContent=byId.get(id).name;$('choices').replaceChildren();for(const tier of [...state.tiers,{id:'pool',name:'Back to collection',color:'#bcf653'}]){const button=document.createElement('button');button.textContent=tier.name;button.style.borderColor=tier.color;button.onclick=()=>{$('picker').close();move(id,tier.id);};$('choices').append(button);}$('picker').showModal();}
  $('title').addEventListener('input',()=>{state.title=$('title').value;save();});$('search').addEventListener('input',renderPool);dropzone($('pool'),'pool');
  $('add').onclick=()=>{if(state.tiers.length>=15)return;state.tiers.push({id:'tier-'+Date.now().toString(36),name:'New',color:'#bcf653',items:[]});save();render();const inputs=document.querySelectorAll('.tier-name');inputs[inputs.length-1].focus();inputs[inputs.length-1].select();};
  $('reset').onclick=()=>ask('Start over?','Your current ranking will be cleared. Export a PNG first if you want to keep it.',()=>{state=fresh();save();render();toast('Your fresh tier list is ready.');});
  $('import').onclick=()=>$('file').click();$('file').onchange=async()=>{const file=$('file').files[0];$('file').value='';if(!file)return;try{if(file.size>30*1024*1024)throw Error('Choose a PNG smaller than 30 MB.');const imported=validate(MonsterPNG.read(new Uint8Array(await file.arrayBuffer())));ask('Import this tier list?','The imported list will replace your current ranking.',()=>{state=imported;save();render();toast('Your tier list has been restored.');});}catch(error){toast(error.message);}};
  function fitText(ctx,text,x,y,maxWidth,size){ctx.font='700 '+size+'px Arial';while(ctx.measureText(text).width>maxWidth&&size>12){size--;ctx.font='700 '+size+'px Arial';}ctx.fillText(text,x,y,maxWidth);}
  async function exportPNG(){
    const button=$('export');button.disabled=true;button.textContent='Creating PNG…';
    try{
      const snapshot=validate(JSON.parse(JSON.stringify(state)));
      const imageMap=new Map();await Promise.all(catalog.map(item=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{imageMap.set(item.id,img);resolve();};img.onerror=()=>reject(Error('An image could not be loaded.'));img.src=item.data;})));
      const width=1400,pad=44,label=128,columns=12,cell=94,heightPer=122;
      const groups=[...snapshot.tiers,...(snapshot.pool.length?[{name:'Not ranked yet',color:'#79866a',items:snapshot.pool}]:[])];
      const heights=groups.map(t=>Math.max(1,Math.ceil(t.items.length/columns))*heightPer);
      const canvas=document.createElement('canvas');canvas.width=width;canvas.height=160+heights.reduce((a,b)=>a+b,0)+76;const ctx=canvas.getContext('2d');
      ctx.fillStyle='#111510';ctx.fillRect(0,0,width,canvas.height);ctx.fillStyle='#bcf653';ctx.font='bold 15px Arial';ctx.fillText('MONSTER TIER',pad,44);ctx.fillStyle='#f2f4ed';fitText(ctx,snapshot.title||'My Monster tier list',pad,104,width-pad*2,40);
      let y=148;groups.forEach((tier,index)=>{const h=heights[index];ctx.fillStyle='#1d231a';ctx.fillRect(pad,y,width-pad*2,h-3);ctx.fillStyle=tier.color;ctx.fillRect(pad,y,label,h-3);ctx.fillStyle='#171b14';ctx.textAlign='center';fitText(ctx,tier.name,pad+label/2,y+h/2+10,label-16,tier.name.length>5?19:36);ctx.textAlign='left';tier.items.forEach((id,i)=>{const img=imageMap.get(id),scale=Math.min(74/img.width,104/img.height);const w=img.width*scale,ih=img.height*scale;ctx.drawImage(img,pad+label+18+(i%columns)*cell+(cell-w)/2,y+Math.floor(i/columns)*heightPer+(heightPer-ih)/2,w,ih);});y+=h;});
      ctx.fillStyle='#9fab91';ctx.font='14px Arial';ctx.fillText("Made with Justin Verstijnen's Monster Tier tool • Import this PNG to keep ranking.",pad,canvas.height-29);
      const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('The PNG could not be created.');const output=MonsterPNG.write(new Uint8Array(await blob.arrayBuffer()),snapshot);const url=URL.createObjectURL(new Blob([output],{type:'image/png'}));const link=document.createElement('a');link.href=url;link.download=(snapshot.title.replace(/[^a-z0-9 -]/gi,'').trim().replace(/\s+/g,'-')||'monster-tier')+'.png';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);toast('PNG exported, including your complete tier list.');
    }catch(error){toast('Export failed: '+error.message);}finally{button.disabled=false;button.textContent='↓  Export PNG';}
  }
  $('export').onclick=exportPNG;render();if(loadError){$('saved').textContent='Saved list not loaded';toast(loadError);}else{try{const probe=key+'.check';localStorage.setItem(probe,'1');localStorage.removeItem(probe);}catch{$('saved').textContent='Local saving unavailable';}}
})();

